// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaqknppocoenmyjzxyhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphcWtucHBvY29lbm15anp4eWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mjc5MzUsImV4cCI6MjA2NzIwMzkzNX0.B7VYcTuWeITjBgCjO_cW7pIprrIqSdsKgH8UuaaWvcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});